// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihlgthgxlpaohrezdlay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlobGd0aGd4bHBhb2hyZXpkbGF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4Mjk5MTAsImV4cCI6MjA2MzQwNTkxMH0.zuN_BIdR3-oyUHx8c0K6R-lz3_WSNQ7zIu0hbWztI80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Enhanced Supabase client configuration with proper headers
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
  },
  global: {
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      'apikey': SUPABASE_PUBLISHABLE_KEY
    },
  },
});